version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /mongodb/db:/data/db
  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./back/
    container_name: back
    restart: always
    ports:
      - "8084:5500"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/back
      - /back/node_modules
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    container_name: front
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./front/.env
    volumes:
      - ./deploy/default.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend